/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments.index'
import { Route as AppointmentsNewRouteImport } from './routes/appointments.new'
import { Route as AppointmentsIdRouteImport } from './routes/appointments.$id'
import { Route as ApiRepairDataRouteImport } from './routes/api.repair-data'
import { Route as ApiPhotosRouteImport } from './routes/api.photos'
import { Route as ApiPhotosKeyRouteImport } from './routes/api.photos.$key'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiWebhooksZapierBookingRouteImport } from './routes/api.webhooks.zapier.booking'

const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppointmentsRoute,
} as any)
const AppointmentsNewRoute = AppointmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppointmentsRoute,
} as any)
const AppointmentsIdRoute = AppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppointmentsRoute,
} as any)
const ApiRepairDataRoute = ApiRepairDataRouteImport.update({
  id: '/api/repair-data',
  path: '/api/repair-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotosRoute = ApiPhotosRouteImport.update({
  id: '/api/photos',
  path: '/api/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotosKeyRoute = ApiPhotosKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiPhotosRoute,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksZapierBookingRoute =
  ApiWebhooksZapierBookingRouteImport.update({
    id: '/api/webhooks/zapier/booking',
    path: '/api/webhooks/zapier/booking',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/clients': typeof ClientsRoute
  '/pricing': typeof PricingRoute
  '/stocks': typeof StocksRoute
  '/api/photos': typeof ApiPhotosRouteWithChildren
  '/api/repair-data': typeof ApiRepairDataRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/photos/$key': typeof ApiPhotosKeyRoute
  '/api/webhooks/zapier/booking': typeof ApiWebhooksZapierBookingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/pricing': typeof PricingRoute
  '/stocks': typeof StocksRoute
  '/api/photos': typeof ApiPhotosRouteWithChildren
  '/api/repair-data': typeof ApiRepairDataRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/photos/$key': typeof ApiPhotosKeyRoute
  '/api/webhooks/zapier/booking': typeof ApiWebhooksZapierBookingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/clients': typeof ClientsRoute
  '/pricing': typeof PricingRoute
  '/stocks': typeof StocksRoute
  '/api/photos': typeof ApiPhotosRouteWithChildren
  '/api/repair-data': typeof ApiRepairDataRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/photos/$key': typeof ApiPhotosKeyRoute
  '/api/webhooks/zapier/booking': typeof ApiWebhooksZapierBookingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/clients'
    | '/pricing'
    | '/stocks'
    | '/api/photos'
    | '/api/repair-data'
    | '/appointments/$id'
    | '/appointments/new'
    | '/appointments/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/photos/$key'
    | '/api/webhooks/zapier/booking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/pricing'
    | '/stocks'
    | '/api/photos'
    | '/api/repair-data'
    | '/appointments/$id'
    | '/appointments/new'
    | '/appointments'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/photos/$key'
    | '/api/webhooks/zapier/booking'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/clients'
    | '/pricing'
    | '/stocks'
    | '/api/photos'
    | '/api/repair-data'
    | '/appointments/$id'
    | '/appointments/new'
    | '/appointments/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/photos/$key'
    | '/api/webhooks/zapier/booking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRouteWithChildren
  ClientsRoute: typeof ClientsRoute
  PricingRoute: typeof PricingRoute
  StocksRoute: typeof StocksRoute
  ApiPhotosRoute: typeof ApiPhotosRouteWithChildren
  ApiRepairDataRoute: typeof ApiRepairDataRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiWebhooksZapierBookingRoute: typeof ApiWebhooksZapierBookingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/appointments/new': {
      id: '/appointments/new'
      path: '/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof AppointmentsNewRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/appointments/$id': {
      id: '/appointments/$id'
      path: '/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof AppointmentsIdRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/api/repair-data': {
      id: '/api/repair-data'
      path: '/api/repair-data'
      fullPath: '/api/repair-data'
      preLoaderRoute: typeof ApiRepairDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photos': {
      id: '/api/photos'
      path: '/api/photos'
      fullPath: '/api/photos'
      preLoaderRoute: typeof ApiPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photos/$key': {
      id: '/api/photos/$key'
      path: '/$key'
      fullPath: '/api/photos/$key'
      preLoaderRoute: typeof ApiPhotosKeyRouteImport
      parentRoute: typeof ApiPhotosRoute
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/zapier/booking': {
      id: '/api/webhooks/zapier/booking'
      path: '/api/webhooks/zapier/booking'
      fullPath: '/api/webhooks/zapier/booking'
      preLoaderRoute: typeof ApiWebhooksZapierBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppointmentsRouteChildren {
  AppointmentsIdRoute: typeof AppointmentsIdRoute
  AppointmentsNewRoute: typeof AppointmentsNewRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
}

const AppointmentsRouteChildren: AppointmentsRouteChildren = {
  AppointmentsIdRoute: AppointmentsIdRoute,
  AppointmentsNewRoute: AppointmentsNewRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
}

const AppointmentsRouteWithChildren = AppointmentsRoute._addFileChildren(
  AppointmentsRouteChildren,
)

interface ApiPhotosRouteChildren {
  ApiPhotosKeyRoute: typeof ApiPhotosKeyRoute
}

const ApiPhotosRouteChildren: ApiPhotosRouteChildren = {
  ApiPhotosKeyRoute: ApiPhotosKeyRoute,
}

const ApiPhotosRouteWithChildren = ApiPhotosRoute._addFileChildren(
  ApiPhotosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRouteWithChildren,
  ClientsRoute: ClientsRoute,
  PricingRoute: PricingRoute,
  StocksRoute: StocksRoute,
  ApiPhotosRoute: ApiPhotosRouteWithChildren,
  ApiRepairDataRoute: ApiRepairDataRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiWebhooksZapierBookingRoute: ApiWebhooksZapierBookingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
